### ISSUE TITLE
Bitmask-based verdict

### ISSUE THREAD

**Issue by minhducsun2002** [vnma0/wafter#101]
Verdicts should be expressed as bit patterns `OR`ed together, allowing quicker checks and easier parsing compared to hardcoded strings.

**Comment by dungwinux** [comment]
@minhducsun2002, what do you mean? The verdict parsing is actually a function, giving you the freedom of parsing the score to your liking. No need to enforce bitmask or anything

**Comment by dungwinux** [comment]
It's gonna be hard to extend, and such optimization is not necessary for now. You may want to prototype idea first, since it is not easy to quickly adapt.
