### ISSUE TITLE
hàm update hoạt động không bình thường

### ISSUE THREAD

**Issue by PineyFutanaristic** [vnma0/wafter#11]
khi sử dụng hàm update, thay vì chỉnh sửa thẳng vào trong database, nó tạo thêm một bản sao khác sau khi thay đổi và đẩy vào database trong khi bản cũ vẫn ở đó.
lẽ ra phải thế này:
`{"source_code":"samplecode","status":"Accepted","date":{"$$date":1546965191350},"user_id":"9mIj2IAhLMNxyAEz","prob_id":"sampleprob","score":40,"penalty":null,"ctype":"OI","_id":"Hdcj3l7G9fFscQ3w"}`
thì nó lại thế này:
`{"source_code":"samplecode","status":"Pending","date":{"$$date":1546965191350},"user_id":"9mIj2IAhLMNxyAEz","prob_id":"sampleprob","score":null,"penalty":null,"ctype":"OI","_id":"Hdcj3l7G9fFscQ3w"}
{"source_code":"samplecode","status":"Accepted","date":{"$$date":1546965191350},"user_id":"9mIj2IAhLMNxyAEz","prob_id":"sampleprob","score":40,"penalty":null,"ctype":"OI","_id":"Hdcj3l7G9fFscQ3w"}`
cú pháp hoàn toàn bình thường theo documentation của nedb, liệu đây là lỗi của máy tôi hay do chương trình

**Comment by dungwinux** [comment]
Hôm nọ test trên trường cũng bị lỗi giống hệt

**Comment by dungwinux** [comment]
Check xem có fix được ko
https://github.com/louischatriot/nedb/issues/551

**Comment by dungwinux** [comment]
"Lỗi" này là do cách hoạt động của NeDB.
https://github.com/louischatriot/nedb/issues/530#issuecomment-331963586
Thế nên đừng sửa nữa
