### ISSUE TITLE
Switch to new build procedure

### ISSUE THREAD

**Issue by dungwinux** [vnma0/wafter#44]
- Uncompressed size: ~35MB
- Compressed size (zip): ~12MB
- Compressed size (7z): ~10MB

Definitely a problem with `pkg` when packaging. Any solutions are welcome.

**Comment by minhducsun2002** [comment]
Tried `strip.exe` from MinGW-w64 project?

**Comment by minhducsun2002** [comment]
```
cipher@magister-mentium [0] ~/Projects/wafter $ npx pkg --targets node10-linux-x64,node10-win-x64 -o dist/wafter  .
> pkg@4.3.7
cipher@magister-mentium [0] ~/Projects/wafter $ ls --size dist/       
total 93448
53200 wafter-linux  40248 wafter-win.exe
cipher@magister-mentium [0] ~/Projects/wafter $ strip dist/*
cipher@magister-mentium [0] ~/Projects/wafter $ ls --size dist/
total 52776
29644 wafter-linux  23132 wafter-win.exe
```

Not really sure if the PE32+ executable can work normally as its ELF counterpart, so try [this](https://github.com/vnma0/wafter/files/2931405/release.zip).

**Comment by dungwinux** [comment]
I've known this a long time ago. That's why I'm putting up this issue

**Comment by dungwinux** [comment]
New proposed build procedure:
1. Compile into one file using `@zeit/ncc`
2. Build into exe using `nexe`. Bundling version here is convenient.

**Comment by dungwinux** [comment]
Test of new procedure @ master
Source file size: 2,894 MB
Binary size: 26,782 MB
