### ISSUE TITLE
Apply version and config in bundle

### ISSUE THREAD

**Issue by dungwinux** [vnma0/wafter#60]
### Issue
- The version on release doesn't match with the version in package.json and the version shown in menu.
- The config was not included in bundle, thus open to user

**Comment by dungwinux** [comment]
Solution 1:
- Set `package.json` in source to be static (i.e: `2.0.0`)
- Set the `index.js` to read the version from `package.json`
- Everytime build run, execute `npm --no-git-tag-version version %APPVEYOR_BUILD_VERSION%`

**Comment by minhducsun2002** [comment]
You can set an environment variable named `BUILD_VER` for example, then reference to that variable in the source code with `process.env`. 

To prevent external data injection and lock-down the version into a plain string, use [`envify`](https://www.npmjs.com/package/envify) (which comes by default with Create React App) to replace the variable reference with it.

**Comment by dungwinux** [comment]
envify seems prominent, will check out

**Comment by dungwinux** [comment]
The first option you given won't work currently, because wafter leave `.env` open. The `.env` may be closed in near future

**Comment by minhducsun2002** [comment]
I didn't mean to use `.env` - in fact, I discourage using `.env` to store configurations. Just set a **real** variable.

**Comment by minhducsun2002** [comment]
[`genversion`](https://www.npmjs.com/package/genversion) is another option to check out.
