### ISSUE TITLE
MemoryStore in production is discouraged

### ISSUE THREAD

**Issue by minhducsun2002** [vnma0/wafter#68]
~Deployment in Heroku :~

~`2019-03-30T00:36:57.735753+00:00 app[web.1]: > node src/index.js`~
~`2019-03-30T00:36:57.735755+00:00 app[web.1]: `~
~`2019-03-30T00:36:57.940564+00:00 app[web.1]: MIRAI Wafter 1.5`~
~`2019-03-30T00:36:57.941837+00:00 app[web.1]: Copyright (c) 2018 Vườn ươm A0. MIT License.`~
~`2019-03-30T00:36:58.202983+00:00 app[web.1]: Warning: connect.session() MemoryStore is not`~
~`2019-03-30T00:36:58.203020+00:00 app[web.1]: designed for a production environment, as it will leak`~
~`2019-03-30T00:36:58.203022+00:00 app[web.1]: memory, and will not scale past a single process.`~

Also reproducible on Linux systems : 
```
$ NODE_ENV=production node src/index.js
MIRAI Wafter 1.5
Copyright (c) 2018 Vườn ươm A0. MIT License.
✔ How can I help you ? · Start server
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.

```

Express will [complain if `NODE_ENV` is `production`](https://github.com/expressjs/session/issues/556), as it is discouraged.

**Comment by dungwinux** [comment]
First, the app is not intended for deploying, so don't upload to heroku, please.
For the problem with express, i will try to investigate further

**Comment by minhducsun2002** [comment]
> Also reproducible on Linux systems :

You see this, probably?

**Comment by dungwinux** [comment]
There will be patch for this tonight, please wait
