### ISSUE TITLE
Allow serving GZip-ped resources from /?

### ISSUE THREAD

**Issue by minhducsun2002** [vnma0/wafter#76]
It takes pretty long time to load 2.5MB of scripts from the network.

**Comment by dungwinux** [comment]
Pinned.
https://expressjs.com/en/advanced/best-practice-performance.html#use-gzip-compression

**Comment by natsukagami** [comment]
It is better to have pre-gzipped scripts rather than compressing on the fly. Maybe with a build script?

**Comment by minhducsun2002** [comment]
I'll modify the build script of Hestia to produce a gzipped version - as part of the building flow.

**Comment by minhducsun2002** [comment]
As with https://github.com/vnma0/wafter/issues/76#issuecomment-483332401, [`express-static-gzip`](https://www.npmjs.com/package/express-static-gzip) can be used instead of compressing on-the-fly. 

We don't like our software to be slow, do we?

**Comment by minhducsun2002** [comment]
See https://github.com/vnma0/hestia/pull/133 for a building script.

**Comment by minhducsun2002** [comment]
Also, @dungwinux, can you make a script to clear the source maps produced by CRA? It is not needed, and in some cases, intruders can leverage them to inject scripts & alter the behaviour of Hestia - something pretty much possible since we do not support HTTPS.

**Comment by dungwinux** [comment]
later, not on this issue

**Comment by minhducsun2002** [comment]
Well I did it anyway - CRA supports doing so.

**Comment by minhducsun2002** [comment]
Well I did it anyway - CRA supports doing so.

**Comment by minhducsun2002** [comment]
The gain from compressing the resources is substantial - at least 30% for short files, and most of the JS files takes 60% less space. For fonts, the gains is nearly 50%.
```
.
├── [1.1k]  asset-manifest.json
├── [ 347]  asset-manifest.json.gz
├── [3.9k]  favicon.ico
├── [3.5k]  favicon.ico.gz
├── [3.8k]  index.html
├── [1.8k]  index.html.gz
├── [ 286]  manifest.json
├── [ 194]  manifest.json.gz
├── [1.6k]  precache-manifest.b100312efdcbda0299c7061a2f68049f.js
├── [ 524]  precache-manifest.b100312efdcbda0299c7061a2f68049f.js.gz
├── [1.0k]  service-worker.js
├── [ 592]  service-worker.js.gz
└── [4.1k]  static
    ├── [4.1k]  css
    │   ├── [ 212]  5.b7043416.chunk.css
    │   ├── [ 126]  5.b7043416.chunk.css.gz
    │   ├── [ 192]  7.0c2bf69a.chunk.css
    │   ├── [ 121]  7.0c2bf69a.chunk.css.gz
    │   ├── [ 889]  main.1243f59c.chunk.css
    │   └── [ 341]  main.1243f59c.chunk.css.gz
    ├── [4.1k]  js
    │   ├── [431k]  0.28facd53.chunk.js
    │   ├── [120k]  0.28facd53.chunk.js.gz
    │   ├── [488k]  3.5a8c14d1.chunk.js
    │   ├── [127k]  3.5a8c14d1.chunk.js.gz
    │   ├── [2.0M]  4.ceaf8509.chunk.js
    │   ├── [469k]  4.ceaf8509.chunk.js.gz
    │   ├── [ 31k]  5.7f6cf64b.chunk.js
    │   ├── [8.0k]  5.7f6cf64b.chunk.js.gz
    │   ├── [9.5k]  6.15e5ba54.chunk.js
    │   ├── [3.2k]  6.15e5ba54.chunk.js.gz
    │   ├── [3.6k]  7.96851b26.chunk.js
    │   ├── [1.3k]  7.96851b26.chunk.js.gz
    │   ├── [2.2k]  8.a0c65e5e.chunk.js
    │   ├── [ 899]  8.a0c65e5e.chunk.js.gz
    │   ├── [ 37k]  main.8e28154c.chunk.js
    │   ├── [8.0k]  main.8e28154c.chunk.js.gz
    │   ├── [3.2k]  runtime~main.0537fcc3.js
    │   └── [1.5k]  runtime~main.0537fcc3.js.gz
    └── [4.1k]  media
        ├── [170k]  Roboto-Bold.7c181887.ttf
        ├── [ 90k]  Roboto-Bold.7c181887.ttf.gz
        ├── [171k]  Roboto-Medium.d52f011b.ttf
        ├── [ 90k]  Roboto-Medium.d52f011b.ttf.gz
        ├── [171k]  Roboto-Regular.18d44f79.ttf
        └── [ 89k]  Roboto-Regular.18d44f79.ttf.gz
```

**Comment by dungwinux** [comment]
Where's the release, then?

**Comment by minhducsun2002** [comment]
Feel free to get the artifacts from AppVeyor. Currently I don't have a way to provide the latest build from `master` - you'll have to build it yourself for quite some time.

**Comment by minhducsun2002** [comment]
[`v1.5.2-20190421.1`](https://github.com/vnma0/hestia/releases/tag/v1.5.2-20190421.1) is online. Feel free to check out.
